PVE_THIN_CLIENT_MODE="DCV"
PVE_THIN_CLIENT_RUNTIME_USER="thinclient"
PVE_THIN_CLIENT_AUTOSTART="1"
PVE_THIN_CLIENT_SPICE_URL=""
PVE_THIN_CLIENT_NOVNC_URL=""
PVE_THIN_CLIENT_BROWSER_BIN="chromium"
PVE_THIN_CLIENT_DCV_URL="dcv://dcv-gateway.example.internal/session/example"
