PVE_THIN_CLIENT_MODE="NOVNC"
PVE_THIN_CLIENT_RUNTIME_USER="thinclient"
PVE_THIN_CLIENT_AUTOSTART="1"
PVE_THIN_CLIENT_SPICE_URL=""
PVE_THIN_CLIENT_NOVNC_URL="https://proxmox.example.internal:8006/?console=kvm"
PVE_THIN_CLIENT_BROWSER_BIN="chromium"
PVE_THIN_CLIENT_DCV_URL=""
