PVE_THIN_CLIENT_MODE="SPICE"
PVE_THIN_CLIENT_RUNTIME_USER="thinclient"
PVE_THIN_CLIENT_AUTOSTART="1"
PVE_THIN_CLIENT_SPICE_URL="spice://proxmox.example.internal:3128"
PVE_THIN_CLIENT_NOVNC_URL=""
PVE_THIN_CLIENT_BROWSER_BIN="chromium"
PVE_THIN_CLIENT_DCV_URL=""
