#!/usr/bin/env bash
set -euo pipefail

THINCLIENT_ARCH="${THINCLIENT_ARCH:-amd64}"
THINCLIENT_LINUX_FLAVOUR="${THINCLIENT_LINUX_FLAVOUR:-}"

if [[ -z "$THINCLIENT_LINUX_FLAVOUR" ]]; then
  case "$THINCLIENT_ARCH" in
    amd64) THINCLIENT_LINUX_FLAVOUR="amd64" ;;
    *)
      echo "Unsupported THINCLIENT_ARCH: $THINCLIENT_ARCH" >&2
      exit 1
      ;;
  esac
fi

BOOT_ARGS="boot=live components username=thinclient hostname=pve-thin-client ip=dhcp quiet loglevel=3 systemd.show_status=0 vt.global_cursor_default=0 splash pve_thin_client.mode=installer"

lb config noauto \
  --mode debian \
  --architectures "$THINCLIENT_ARCH" \
  --initsystem systemd \
  --distribution bookworm \
  --binary-images iso-hybrid \
  --debian-installer false \
  --archive-areas "main contrib non-free non-free-firmware" \
  --linux-packages "none" \
  --linux-flavours "$THINCLIENT_LINUX_FLAVOUR" \
  --firmware-chroot true \
  --firmware-binary true \
  --mirror-bootstrap "http://deb.debian.org/debian" \
  --mirror-chroot "http://deb.debian.org/debian" \
  --mirror-binary "http://deb.debian.org/debian" \
  --mirror-chroot-security "http://deb.debian.org/debian-security" \
  --mirror-binary-security "http://deb.debian.org/debian-security" \
  --security false \
  --bootappend-live "$BOOT_ARGS" \
  "$@"
