#!/usr/bin/env bash
set -euo pipefail

CONFIG_DIR="${1:-/etc/pve-thin-client}"

MODE="${MODE:-MOONLIGHT}"
RUNTIME_USER="${RUNTIME_USER:-thinclient}"
AUTOSTART="${AUTOSTART:-1}"
PROFILE_NAME="${PROFILE_NAME:-default}"
HOSTNAME_VALUE="${HOSTNAME_VALUE:-pve-thin-client}"
CONNECTION_METHOD="${CONNECTION_METHOD:-direct}"
MOONLIGHT_HOST="${MOONLIGHT_HOST:-}"
MOONLIGHT_APP="${MOONLIGHT_APP:-Desktop}"
MOONLIGHT_BIN="${MOONLIGHT_BIN:-moonlight}"
MOONLIGHT_RESOLUTION="${MOONLIGHT_RESOLUTION:-auto}"
MOONLIGHT_FPS="${MOONLIGHT_FPS:-60}"
MOONLIGHT_BITRATE="${MOONLIGHT_BITRATE:-20000}"
MOONLIGHT_VIDEO_CODEC="${MOONLIGHT_VIDEO_CODEC:-H.264}"
MOONLIGHT_VIDEO_DECODER="${MOONLIGHT_VIDEO_DECODER:-auto}"
MOONLIGHT_AUDIO_CONFIG="${MOONLIGHT_AUDIO_CONFIG:-stereo}"
MOONLIGHT_ABSOLUTE_MOUSE="${MOONLIGHT_ABSOLUTE_MOUSE:-1}"
MOONLIGHT_QUIT_AFTER="${MOONLIGHT_QUIT_AFTER:-0}"
SUNSHINE_API_URL="${SUNSHINE_API_URL:-}"
PROXMOX_SCHEME="${PROXMOX_SCHEME:-https}"
PROXMOX_HOST="${PROXMOX_HOST:-}"
PROXMOX_PORT="${PROXMOX_PORT:-8006}"
PROXMOX_NODE="${PROXMOX_NODE:-}"
PROXMOX_VMID="${PROXMOX_VMID:-}"
PROXMOX_REALM="${PROXMOX_REALM:-pam}"
PROXMOX_VERIFY_TLS="${PROXMOX_VERIFY_TLS:-0}"
BEAGLE_MANAGER_URL="${BEAGLE_MANAGER_URL:-}"
NETWORK_MODE="${NETWORK_MODE:-dhcp}"
NETWORK_INTERFACE="${NETWORK_INTERFACE:-}"
NETWORK_STATIC_ADDRESS="${NETWORK_STATIC_ADDRESS:-}"
NETWORK_STATIC_PREFIX="${NETWORK_STATIC_PREFIX:-24}"
NETWORK_GATEWAY="${NETWORK_GATEWAY:-}"
NETWORK_DNS_SERVERS="${NETWORK_DNS_SERVERS:-1.1.1.1 8.8.8.8}"
CONNECTION_USERNAME="${CONNECTION_USERNAME:-}"
CONNECTION_PASSWORD="${CONNECTION_PASSWORD:-}"
CONNECTION_TOKEN="${CONNECTION_TOKEN:-}"
BEAGLE_MANAGER_TOKEN="${BEAGLE_MANAGER_TOKEN:-}"
SUNSHINE_USERNAME="${SUNSHINE_USERNAME:-}"
SUNSHINE_PASSWORD="${SUNSHINE_PASSWORD:-}"
SUNSHINE_PIN="${SUNSHINE_PIN:-}"

if [[ "$MODE" != "MOONLIGHT" ]]; then
  echo "Beagle OS supports only MODE=MOONLIGHT." >&2
  exit 1
fi

install -d -m 0755 "$CONFIG_DIR"

cat > "$CONFIG_DIR/thinclient.conf" <<EOF
# pve-thin-client runtime configuration
PVE_THIN_CLIENT_MODE="$MODE"
PVE_THIN_CLIENT_RUNTIME_USER="$RUNTIME_USER"
PVE_THIN_CLIENT_AUTOSTART="$AUTOSTART"
PVE_THIN_CLIENT_PROFILE_NAME="$PROFILE_NAME"
PVE_THIN_CLIENT_HOSTNAME="$HOSTNAME_VALUE"
PVE_THIN_CLIENT_CONNECTION_METHOD="$CONNECTION_METHOD"
PVE_THIN_CLIENT_MOONLIGHT_HOST="$MOONLIGHT_HOST"
PVE_THIN_CLIENT_MOONLIGHT_APP="$MOONLIGHT_APP"
PVE_THIN_CLIENT_MOONLIGHT_BIN="$MOONLIGHT_BIN"
PVE_THIN_CLIENT_MOONLIGHT_RESOLUTION="$MOONLIGHT_RESOLUTION"
PVE_THIN_CLIENT_MOONLIGHT_FPS="$MOONLIGHT_FPS"
PVE_THIN_CLIENT_MOONLIGHT_BITRATE="$MOONLIGHT_BITRATE"
PVE_THIN_CLIENT_MOONLIGHT_VIDEO_CODEC="$MOONLIGHT_VIDEO_CODEC"
PVE_THIN_CLIENT_MOONLIGHT_VIDEO_DECODER="$MOONLIGHT_VIDEO_DECODER"
PVE_THIN_CLIENT_MOONLIGHT_AUDIO_CONFIG="$MOONLIGHT_AUDIO_CONFIG"
PVE_THIN_CLIENT_MOONLIGHT_ABSOLUTE_MOUSE="$MOONLIGHT_ABSOLUTE_MOUSE"
PVE_THIN_CLIENT_MOONLIGHT_QUIT_AFTER="$MOONLIGHT_QUIT_AFTER"
PVE_THIN_CLIENT_SUNSHINE_API_URL="$SUNSHINE_API_URL"
PVE_THIN_CLIENT_PROXMOX_SCHEME="$PROXMOX_SCHEME"
PVE_THIN_CLIENT_PROXMOX_HOST="$PROXMOX_HOST"
PVE_THIN_CLIENT_PROXMOX_PORT="$PROXMOX_PORT"
PVE_THIN_CLIENT_PROXMOX_NODE="$PROXMOX_NODE"
PVE_THIN_CLIENT_PROXMOX_VMID="$PROXMOX_VMID"
PVE_THIN_CLIENT_PROXMOX_REALM="$PROXMOX_REALM"
PVE_THIN_CLIENT_PROXMOX_VERIFY_TLS="$PROXMOX_VERIFY_TLS"
PVE_THIN_CLIENT_BEAGLE_MANAGER_URL="$BEAGLE_MANAGER_URL"
EOF

cat > "$CONFIG_DIR/network.env" <<EOF
PVE_THIN_CLIENT_NETWORK_MODE="$NETWORK_MODE"
PVE_THIN_CLIENT_NETWORK_INTERFACE="$NETWORK_INTERFACE"
PVE_THIN_CLIENT_NETWORK_STATIC_ADDRESS="$NETWORK_STATIC_ADDRESS"
PVE_THIN_CLIENT_NETWORK_STATIC_PREFIX="$NETWORK_STATIC_PREFIX"
PVE_THIN_CLIENT_NETWORK_GATEWAY="$NETWORK_GATEWAY"
PVE_THIN_CLIENT_NETWORK_DNS_SERVERS="$NETWORK_DNS_SERVERS"
EOF

cat > "$CONFIG_DIR/credentials.env" <<EOF
PVE_THIN_CLIENT_CONNECTION_USERNAME="$CONNECTION_USERNAME"
PVE_THIN_CLIENT_CONNECTION_PASSWORD="$CONNECTION_PASSWORD"
PVE_THIN_CLIENT_CONNECTION_TOKEN="$CONNECTION_TOKEN"
PVE_THIN_CLIENT_BEAGLE_MANAGER_TOKEN="$BEAGLE_MANAGER_TOKEN"
PVE_THIN_CLIENT_SUNSHINE_USERNAME="$SUNSHINE_USERNAME"
PVE_THIN_CLIENT_SUNSHINE_PASSWORD="$SUNSHINE_PASSWORD"
PVE_THIN_CLIENT_SUNSHINE_PIN="$SUNSHINE_PIN"
EOF

# These files are sourced by the unprivileged runtime user after boot.
# Keep them readable on the installed live medium so the session can start.
chmod 0644 "$CONFIG_DIR/thinclient.conf" "$CONFIG_DIR/network.env" "$CONFIG_DIR/credentials.env"
