# pve-thin-client runtime configuration
PVE_THIN_CLIENT_MODE="@MODE@"
PVE_THIN_CLIENT_RUNTIME_USER="@RUNTIME_USER@"
PVE_THIN_CLIENT_AUTOSTART="1"

# SPICE mode
PVE_THIN_CLIENT_SPICE_URL="@SPICE_URL@"

# noVNC mode
PVE_THIN_CLIENT_NOVNC_URL="@NOVNC_URL@"
PVE_THIN_CLIENT_BROWSER_BIN="@BROWSER_BIN@"

# DCV mode
PVE_THIN_CLIENT_DCV_URL="@DCV_URL@"
